export enum EEventType{
    IfFollow=1,
    Speed=2,
    SpeedDir=3,
    Acr=4,
    AcrDir=5,
    Diffuse_Radius=6,
    Diffuse_Rotate=7,
    Count=8,
    Interval=9,
    Degree=10,
    Range=11,
    LifeCycle=101,//子弹生命
    ImagePath=102,//子弹图片
    RedColor=103,//子弹红色值
    GreenColor=104,//子弹绿色值
    BlueColor=105,//子弹蓝色值
    BulletSpeed=106,//子弹标量速度
    BulletSpeedDir=107,//子弹方向
    BulletAcr=108,//子弹加速度标量
    BulletAcrDir=109,//子弹加速度方向
    XScale=110,//横向
    YScale=111,//纵向
    Normal=201,//恢复所有变化
}
