export enum EEventType{
    IfFollow="if_follow",
    Speed="speed",
    SpeedDir="speed_dir",
    Acc="acc",
    AccDir="acc_dir",
    Diffuse_Spread="diffuse_spread",
    Diffuse_Rotate="duffuse_rotate",
    Count="count",
    Interval="interval",
    Skew="skew",
    Range="range",
    Axis="axis",
    LifeCycle="life_cycle",//子弹生命
    ImagePath="image_path",//子弹图片
    RedColor="red_color",//子弹红色值
    GreenColor="green_color",//子弹绿色值
    BlueColor="blue_color",//子弹蓝色值
    BulletSpeed="bullet_speed",//子弹标量速度
    BulletSpeedDir="bullet_speed_dir",//子弹方向
    BulletAcc="bullet_acc",//子弹加速度标量
    BulletAccDir="bullet_acc_dir",//子弹加速度方向
    XScale="xScale",//横向
    YScale="yScale",//纵向
    Normal="normal",//恢复所有变化
}
